### ISSUE TITLE
Add support for plt.pause(...)

### ISSUE THREAD

**Issue by maxg203** [pyodide/matplotlib-pyodide#41]
Matplotlib's `plt.pause(...)` causes the below error. It will error seemingly because it calls `plt.show(block=False)`, whereas this repository does not appear to support calls to `plt.show` with pass-through kwargs.

Full stacktrace:
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/\_pyodide/\_base.py", line 571, in eval\_code\_async
    await CodeRunner(
  File "/lib/python311.zip/\_pyodide/\_base.py", line 394, in run\_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\<exec>", line 113, in \<module>
  File "\<exec>", line 101, in main
  File "/lib/python3.11/site-packages/matplotlib/pyplot.py", line 568, in pause
    show(block=False)
  File "/lib/python3.11/site-packages/matplotlib/pyplot.py", line 389, in show
    return \_get\_backend\_mod().show(\*args, \*\*kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: \_BackendWasmCoreAgg.show() got an unexpected keyword argument 'block'
```

**Comment by maxg203** [comment]
I will submit a PR to fix this, although I can't assign myself to this issue I think due to a permission issue.

**Comment by hoodmane** [comment]
Thanks @maxg203!

**Comment by maxg203** [comment]
Fixed in PR #42
